/**
 * Central API route catalog shared by the future ASP.NET Core repositories.
 * Mobile screens must never hard-code backend paths.
 */
export const API_ENDPOINTS = {
  auth: {
    login: "/api/auth/login",
    registerUser: "/api/auth/register/user",
    registerOrganization: "/api/auth/register/organization",
    refresh: "/api/auth/refresh",
    logout: "/api/auth/logout",
    logoutAll: "/api/auth/logout-all",
    sendPhoneVerification: "/api/auth/phone-verification/send",
    verifyPhone: "/api/auth/phone-verification/verify",
    sendPasswordReset: "/api/auth/password-reset/send",
    verifyPasswordReset: "/api/auth/password-reset/verify",
    completePasswordReset: "/api/auth/password-reset/complete",
  },
  profile: {
    me: "/api/profile/me",
    changePassword: "/api/profile/change-password",
  },
  lookups: {
    governorates: "/api/lookups/governorates",
    regions: (governorateId: string) => `/api/lookups/governorates/${encodeURIComponent(governorateId)}/regions`,
    areas: (governorateId: string) => `/api/lookups/governorates/${encodeURIComponent(governorateId)}/areas`,
  },
  organizations: {
    list: "/api/organizations",
    byId: (id: string) => `/api/organizations/${encodeURIComponent(id)}`,
    me: "/api/organizations/me",
    documents: "/api/organizations/me/documents",
  },
  reports: {
    list: "/api/reports",
    create: "/api/reports",
    byId: (id: string) => `/api/reports/${encodeURIComponent(id)}`,
    mine: "/api/reports/mine",
  },
  rescueMissions: {
    mine: "/api/rescue-missions/mine",
    byId: (id: string) => `/api/rescue-missions/${encodeURIComponent(id)}`,
    details: (id: string) => `/api/rescue-missions/${encodeURIComponent(id)}/details`,
    accept: (id: string) => `/api/rescue-missions/${encodeURIComponent(id)}/accept`,
    onTheWay: (id: string) => `/api/rescue-missions/${encodeURIComponent(id)}/on-the-way`,
    arrive: (id: string) => `/api/rescue-missions/${encodeURIComponent(id)}/arrive`,
    rescue: (id: string) => `/api/rescue-missions/${encodeURIComponent(id)}/rescue`,
    complete: (id: string) => `/api/rescue-missions/${encodeURIComponent(id)}/complete`,
    cancel: (id: string) => `/api/rescue-missions/${encodeURIComponent(id)}/cancel`,
  },
  adoption: {
    listings: "/api/adoption/listings",
    byId: (id: string) => `/api/adoption/listings/${encodeURIComponent(id)}`,
    mine: "/api/adoption/listings/mine",
    mineById: (id: string) => `/api/adoption/listings/mine/${encodeURIComponent(id)}`,
    submit: (id: string) => `/api/adoption/listings/${encodeURIComponent(id)}/submit`,
    applications: "/api/adoption/applications",
    myApplications: "/api/adoption/applications/mine",
    myApplicationById: (id: string) => `/api/adoption/applications/mine/${encodeURIComponent(id)}`,
    listingApplications: (id: string) => `/api/adoption/listings/${encodeURIComponent(id)}/applications`,
    listingApplicationById: (listingId: string, applicationId: string) => `/api/adoption/listings/${encodeURIComponent(listingId)}/applications/${encodeURIComponent(applicationId)}`,
    acceptApplication: (listingId: string, applicationId: string) => `/api/adoption/listings/${encodeURIComponent(listingId)}/applications/${encodeURIComponent(applicationId)}/accept`,
    rejectApplication: (listingId: string, applicationId: string) => `/api/adoption/listings/${encodeURIComponent(listingId)}/applications/${encodeURIComponent(applicationId)}/reject`,
    withdrawApplication: (applicationId: string) => `/api/adoption/applications/${encodeURIComponent(applicationId)}/withdraw`,
    confirmApplicantHandover: (applicationId: string) => `/api/adoption/applications/${encodeURIComponent(applicationId)}/confirm-handover`,
    confirmOwnerHandover: (listingId: string, applicationId: string) => `/api/adoption/listings/${encodeURIComponent(listingId)}/applications/${encodeURIComponent(applicationId)}/owner-confirm-handover`,
    reserve: (id: string) => `/api/adoption/listings/${encodeURIComponent(id)}/reserve`,
    markAdopted: (id: string) => `/api/adoption/listings/${encodeURIComponent(id)}/mark-adopted`,
    close: (id: string) => `/api/adoption/listings/${encodeURIComponent(id)}/close`,
  },
  feedingPoints: {
    list: "/api/feeding-points",
    byId: (id: string) => `/api/feeding-points/${encodeURIComponent(id)}`,
    submissions: "/api/feeding-points/submissions",
    mySubmissions: "/api/feeding-points/submissions/mine",
    refills: (id: string) => `/api/feeding-points/${encodeURIComponent(id)}/refills`,
    issues: (id: string) => `/api/feeding-points/${encodeURIComponent(id)}/issues`,
  },
  map: {
    entities: "/api/map/entities",
    myEntities: "/api/map/entities/mine",
    myEntityById: (id: string) => `/api/map/entities/mine/${encodeURIComponent(id)}`,
    requests: "/api/map/requests",
    myRequests: "/api/map/requests/mine",
    requestById: (id: string) => `/api/map/requests/${encodeURIComponent(id)}`,
    resubmitRequest: (id: string) => `/api/map/requests/${encodeURIComponent(id)}/resubmit`,
    cancelRequest: (id: string) => `/api/map/requests/${encodeURIComponent(id)}/cancel`,
  },
  donations: {
    campaigns: "/api/donation-campaigns",
    byId: (id: string) => `/api/donation-campaigns/${encodeURIComponent(id)}`,
    mine: "/api/donation-campaigns/mine",
    submit: (id: string) => `/api/donation-campaigns/${encodeURIComponent(id)}/submit`,
    pause: (id: string) => `/api/donation-campaigns/${encodeURIComponent(id)}/pause`,
    resume: (id: string) => `/api/donation-campaigns/${encodeURIComponent(id)}/resume`,
    close: (id: string) => `/api/donation-campaigns/${encodeURIComponent(id)}/close`,
    campaignTransfers: (id: string) => `/api/donation-campaigns/${encodeURIComponent(id)}/transfers`,
    transfers: "/api/donation-transfers",
    myTransfers: "/api/donation-transfers/mine",
    transferById: (id: string) => `/api/donation-transfers/${encodeURIComponent(id)}`,
    transferProviders: "/api/donation-transfers/providers",
  },
  advertisements: {
    byPlacement: (placement: string) => `/api/advertisements?placement=${encodeURIComponent(placement)}`,
  },
  notifications: {
    list: "/api/notifications",
    unreadCount: "/api/notifications/unread-count",
    readAll: "/api/notifications/read-all",
    markRead: (id: string) => `/api/notifications/${encodeURIComponent(id)}/read`,
    devices: "/api/notifications/devices",
  },
  content: {
    articles: "/api/content/articles",
    articleById: (id: string) => `/api/content/articles/${encodeURIComponent(id)}`,
    successStories: "/api/content/success-stories",
    successStoryById: (id: string) => `/api/content/success-stories/${encodeURIComponent(id)}`,
    faq: "/api/content/faq",
  },
  uploads: {
    create: "/api/uploads",
    byId: (id: string) => `/api/uploads/${encodeURIComponent(id)}`,
  },
} as const;
