import { StyleSheet } from "react-native";

import { TYPOGRAPHY, RADIUS, COLORS, FONTS, PALETTE } from "@/src/theme";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: PALETTE.neutral25,
  },
  keyboardView: {
    flex: 1,
  },
  screen: {
    flex: 1,
    width: "100%",
    overflow: "hidden",
    backgroundColor: PALETTE.neutral25,
  },
  topGlow: {
    position: "absolute",
    backgroundColor: COLORS.divider,
  },
  bottomGlow: {
    position: "absolute",
    backgroundColor: COLORS.divider,
  },
  pageHeader: { backgroundColor: "transparent" },
  scrollContent: {
    flexGrow: 1,
    width: "100%",
    alignItems: "center",
  },
  content: {
    flexGrow: 1,
    alignSelf: "center",
    justifyContent: "center",
    paddingBottom: 8,
  },
  illustrationContainer: {
    position: "relative",
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 22,
  },
  illustrationHalo: {
    position: "absolute",
    backgroundColor: COLORS.dangerSoft,
  },
  lockShackle: {
    position: "absolute",
    borderColor: COLORS.primary,
    backgroundColor: "transparent",
  },
  lockBody: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.dangerSoft,
    borderWidth: 2,
    borderColor: COLORS.textSecondary,
    shadowColor: COLORS.primaryStrong,
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  keyholeCircle: {
    width: 20,
    height: 20,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.textSecondary,
  },
  keyholeStem: {
    width: 8,
    height: 25,
    marginTop: -3,
    borderBottomLeftRadius: RADIUS.xs,
    borderBottomRightRadius: RADIUS.xs,
    backgroundColor: COLORS.textSecondary,
  },
  passwordBadge: {
    position: "absolute",
    minWidth: 92,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.surfaceSubtle,
    borderWidth: 2,
    borderColor: COLORS.textSecondary,
    paddingHorizontal: 12,
  },
  passwordStars: {
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.primary,
    letterSpacing: 1,
    textAlign: "center",
  },
  refreshBadge: {
    position: "absolute",
    width: 62,
    height: 62,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.primary,
    borderWidth: 2,
    borderColor: COLORS.textSecondary,
  },
  sparkleOne: {
    position: "absolute",
  },
  sparkleTwo: {
    position: "absolute",
  },
  header: {
    width: "100%",
    alignItems: "center",
    marginBottom: 26,
  },
  title: {
    fontFamily: FONTS.bold,
    color: COLORS.text,
    textAlign: "center",
  },
  description: {
    maxWidth: 390,
    marginTop: 7,
    fontFamily: FONTS.regular,
    color: COLORS.textMuted,
    textAlign: "center",
  },
  form: {
    width: "100%",
  },
  phoneInput: {
    marginBottom: 6,
  },
  generalError: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
    paddingHorizontal: 13,
    paddingVertical: 11,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.primarySoft,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
  },
  generalErrorText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 20,
    color: COLORS.warning,
    textAlign: "right",
  },
  submitButton: {
    direction: "ltr",
    width: "100%",
    marginTop: 6,
    paddingVertical: 0,
    shadowColor: COLORS.primaryPressed,
    shadowOffset: {
      width: 0,
      height: 9,
    },
    shadowOpacity: 0.22,
    shadowRadius: 13,
    elevation: 7,
  },
  submitButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.icon,
    textAlign: "center",
  },
  footer: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 5,
    marginTop: 72,
    paddingBottom: 4,
  },
  footerText: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.textMuted,
    textAlign: "center",
  },
  loginLink: {
    minHeight: 34,
    justifyContent: "center",
    borderRadius: RADIUS.xs,
  },
  loginLinkText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "center",
  },
  linkPressed: {
    opacity: 0.55,
    transform: [{ scale: 0.96 }],
  },
});

export default styles;
