import { StyleSheet } from "react-native";

import { TYPOGRAPHY, RADIUS, COLORS, FONTS, PALETTE } from "@/src/theme";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: PALETTE.neutral25,
  },
  screen: {
    flex: 1,
    width: "100%",
    overflow: "hidden",
    backgroundColor: PALETTE.neutral25,
  },
  pageHeader: { backgroundColor: "transparent" },
  topGlow: {
    position: "absolute",
    backgroundColor: COLORS.divider,
  },
  bottomGlow: {
    position: "absolute",
    backgroundColor: COLORS.divider,
  },
  topBar: {
    width: "100%",
    minHeight: 58,
    flexDirection: "row", direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 4,
  },
  topBarSpacer: {
    width: 46,
    height: 46,
  },
  backButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.disabledSurface,
  },
  backButtonPressed: {
    opacity: 0.65,
    transform: [{ scale: 0.94 }],
  },
  scrollContent: {
    flexGrow: 1,
    width: "100%",
    alignItems: "center",
  },
  content: {
    flexGrow: 1,
    alignSelf: "center",
    justifyContent: "center",
    paddingBottom: 8,
  },
  illustrationContainer: {
    position: "relative",
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  illustrationHalo: {
    position: "absolute",
    backgroundColor: COLORS.dangerSoft,
  },
  shield: {
    position: "relative",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: COLORS.textSecondary,
    backgroundColor: COLORS.dangerSoft,
    shadowColor: COLORS.primaryStrong,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.16,
    shadowRadius: 14,
    elevation: 5,
  },
  shieldLeft: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: "50%",
    backgroundColor: COLORS.dangerSoft,
  },
  shieldRight: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: "50%",
    backgroundColor: COLORS.primarySoft,
  },
  shieldInner: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  successCircle: {
    width: 76,
    height: 76,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.border,
    borderWidth: 2,
    borderColor: COLORS.secondaryStrong,
  },
  lockBadge: {
    position: "absolute",
    width: 55,
    height: 62,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  lockShackle: {
    position: "absolute",
    top: 0,
    width: 29,
    height: 31,
    borderWidth: 4,
    borderColor: COLORS.textSecondary,
    borderBottomWidth: 0,
    borderTopLeftRadius: RADIUS.lg,
    borderTopRightRadius: RADIUS.lg,
    backgroundColor: "transparent",
  },
  lockBody: {
    width: 52,
    height: 43,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.borderStrong,
    borderWidth: 2,
    borderColor: COLORS.textSecondary,
  },
  sparkleOne: {
    position: "absolute",
    top: "16%",
    left: "10%",
  },
  sparkleTwo: {
    position: "absolute",
    right: "7%",
    bottom: "18%",
  },
  header: {
    width: "100%",
    alignItems: "center",
    marginBottom: 28,
  },
  title: {
    maxWidth: 410,
    fontFamily: FONTS.bold,
    color: COLORS.text,
    textAlign: "center",
  },
  description: {
    maxWidth: 400,
    marginTop: 8,
    fontFamily: FONTS.regular,
    color: COLORS.textMuted,
    textAlign: "center",
  },
  statusCard: {
    width: "100%",
    paddingHorizontal: 20,
    paddingVertical: 18,
    borderRadius: RADIUS.lg,
    backgroundColor: PALETTE.neutral0,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    shadowColor: COLORS.textMuted,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  statusRow: {
    width: "100%",
    flexDirection: "row", direction: "rtl",
    alignItems: "center",
    gap: 12,
  },
  statusIcon: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.secondaryStrong,
  },
  statusText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    lineHeight: 24,
    color: COLORS.icon,
    textAlign: "right",
  },
  statusDivider: {
    width: "100%",
    height: 1,
    marginVertical: 14,
    backgroundColor: COLORS.divider,
  },
  actions: {
    width: "100%",
    marginTop: 46,
    alignItems: "center",
  },
  loginButton: {
    direction: "ltr",
    width: "100%",
    paddingVertical: 0,
    shadowColor: COLORS.primaryPressed,
    shadowOffset: {
      width: 0,
      height: 9,
    },
    shadowOpacity: 0.22,
    shadowRadius: 13,
    elevation: 7,
  },
  loginButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.icon,
    textAlign: "center",
  },
  homeButton: {
    minHeight: 44,
    flexDirection: "row", direction: "rtl",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    marginTop: 18,
    paddingHorizontal: 14,
    borderRadius: RADIUS.sm,
  },
  homeButtonPressed: {
    opacity: 0.55,
    transform: [{ scale: 0.96 }],
  },
  homeButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "center",
  },
});

export default styles;
