import { StyleSheet } from "react-native";

import { RADIUS, COLORS, FONTS, PALETTE, TYPOGRAPHY } from "@/src/theme";

export const registrationSuccessStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.surface,
  },
  scrollView: {
    flex: 1,
    width: "100%",
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: "center",
    paddingTop: 12,
    paddingBottom: 28,
  },
  content: {
    alignSelf: "center",
  },
  brandRow: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    marginBottom: 16,
  },
  brandText: {
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h1.fontSize,
    color: COLORS.text,
  },
  brandAccent: {
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h1.fontSize,
    color: COLORS.primary,
  },
  heroCard: {
    position: "relative",
    overflow: "hidden",
    width: "100%",
    alignItems: "center",
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 21,
    borderRadius: RADIUS["2xl"],
    borderWidth: 1,
    borderColor: COLORS.divider,
    backgroundColor: PALETTE.neutral0,
  },
  heroDecorationOne: {
    position: "absolute",
    top: -45,
    right: -35,
    width: 130,
    height: 130,
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.primarySoft,
  },
  heroDecorationTwo: {
    position: "absolute",
    bottom: -55,
    left: -45,
    width: 140,
    height: 140,
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.infoSoft,
  },
  heroIconHalo: {
    position: "relative",
    width: 102,
    height: 102,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.dangerSoft,
  },
  heroIconCircle: {
    width: 74,
    height: 74,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS["2xl"],
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: PALETTE.neutral0,
  },
  heroCheck: {
    position: "absolute",
    right: 2,
    bottom: 7,
    width: 29,
    height: 29,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.lg,
    borderWidth: 3,
    borderColor: COLORS.dangerSoft,
    backgroundColor: PALETTE.green700,
  },
  rolePill: {
    marginTop: 13,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primarySoft,
  },
  rolePillText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "center",
  },
  title: {
    marginTop: 12,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h1.fontSize,
    lineHeight: TYPOGRAPHY.h1.lineHeight,
    color: COLORS.text,
    textAlign: "center",
    writingDirection: "rtl",
  },
  description: {
    maxWidth: 430,
    marginTop: 7,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    lineHeight: 23,
    color: COLORS.textMuted,
    textAlign: "center",
    writingDirection: "rtl",
  },
  statusCard: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 13,
    marginTop: 14,
    paddingHorizontal: 15,
    paddingVertical: 14,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
  },
  activeStatusCard: {
    borderColor: COLORS.border,
    backgroundColor: COLORS.secondarySoft,
  },
  pendingStatusCard: {
    borderColor: COLORS.border,
    backgroundColor: COLORS.dangerSoft,
  },
  statusIcon: {
    width: 47,
    height: 47,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.lg,
  },
  activeStatusIcon: {
    backgroundColor: COLORS.disabledSurface,
  },
  pendingStatusIcon: {
    backgroundColor: COLORS.primarySoft,
  },
  statusTextContainer: {
    flex: 1,
  },
  statusTitleRow: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 6,
  },
  statusLabel: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.textMuted,
    textAlign: "right",
    writingDirection: "rtl",
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: RADIUS.xs,
  },
  activeStatusDot: {
    backgroundColor: PALETTE.green700,
  },
  pendingStatusDot: {
    backgroundColor: COLORS.primaryPressed,
  },
  statusTitle: {
    marginTop: 3,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    textAlign: "right",
    writingDirection: "rtl",
  },
  activeStatusTitle: {
    color: COLORS.secondaryStrong,
  },
  pendingStatusTitle: {
    color: COLORS.primaryStrong,
  },
  statusDescription: {
    marginTop: 2,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    lineHeight: 18,
    color: COLORS.textMuted,
    textAlign: "right",
    writingDirection: "rtl",
  },
  sectionHeader: {
    width: "100%",
    marginTop: 24,
    marginBottom: 12,
  },
  sectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h2.fontSize,
    color: COLORS.icon,
    textAlign: "right",
    writingDirection: "rtl",
  },
  sectionDescription: {
    marginTop: 4,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 19,
    color: COLORS.textMuted,
    textAlign: "right",
    writingDirection: "rtl",
  },
  capabilitiesCard: {
    width: "100%",
    overflow: "hidden",
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.divider,
    backgroundColor: PALETTE.neutral0,
  },
  capabilityRow: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "flex-start",
    gap: 11,
    paddingHorizontal: 15,
    paddingVertical: 14,
  },
  capabilityRowBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.divider,
  },
  capabilityCheck: {
    width: 25,
    height: 25,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
    borderRadius: RADIUS.md,
    backgroundColor: PALETTE.green700,
  },
  capabilityTextContainer: {
    flex: 1,
  },
  capabilityTitleRow: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 7,
  },
  capabilityTitle: {
    flex: 1,
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "right",
    writingDirection: "rtl",
  },
  capabilityDescription: {
    marginTop: 4,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    lineHeight: 18,
    color: COLORS.textMuted,
    textAlign: "right",
    writingDirection: "rtl",
  },
  profileCard: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 11,
    marginTop: 18,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
  },
  profileIcon: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.xl,
    backgroundColor: PALETTE.neutral0,
  },
  profileTextContainer: {
    flex: 1,
  },
  profileTitle: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "right",
    writingDirection: "rtl",
  },
  profileDescription: {
    marginTop: 2,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.iconMuted,
    textAlign: "right",
    writingDirection: "rtl",
  },
  progressContainer: {
    alignItems: "center",
    gap: 5,
  },
  progressText: {
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.secondaryStrong,
  },
  progressTrack: {
    width: 56,
    height: 6,
    overflow: "hidden",
    borderRadius: RADIUS.xs,
    backgroundColor: COLORS.border,
  },
  progressFill: {
    width: "60%",
    height: "100%",
    borderRadius: RADIUS.xs,
    backgroundColor: COLORS.secondaryStrong,
  },
  primaryButton: {
    width: "100%",
    minHeight: 57,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    marginTop: 22,
    borderRadius: RADIUS.lg,
    backgroundColor: PALETTE.orange500,
  },
  primaryButtonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  primaryButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: PALETTE.neutral0,
    textAlign: "center",
  },
  secondaryButton: {
    width: "100%",
    minHeight: 54,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    borderRadius: RADIUS.lg,
    borderWidth: 1.5,
    borderColor: COLORS.iconMuted,
    backgroundColor: PALETTE.neutral0,
  },
  secondaryButtonPressed: {
    opacity: 0.65,
  },
  secondaryButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: COLORS.secondaryStrong,
    textAlign: "center",
  },
});
