import { StyleSheet } from "react-native";
import { RADIUS, COLORS, FONTS, PALETTE, TYPOGRAPHY } from "@/src/theme";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  keyboardView: { flex: 1 },
  screen: { flex: 1, backgroundColor: COLORS.background },
  pageHeader: { backgroundColor: COLORS.background },
  topBar: {
    minHeight: 58,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
  },
  topBarTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.text,
    textAlign: "center",
    writingDirection: "rtl",
  },
  topBarSpacer: { width: 46, height: 46 },
  backButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.disabledSurface,
  },
  backButtonPressed: { opacity: 0.65, transform: [{ scale: 0.94 }] },
  progressArea: { paddingTop: 4, paddingBottom: 18 },
  progressLabels: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  progressTitle: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  stepText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.primary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  progressTrack: {
    width: "100%",
    height: 5,
    overflow: "hidden",
    borderRadius: RADIUS.full,
    backgroundColor: PALETTE.neutral250,
  },
  progressFill: {
    width: "66.666%",
    height: "100%",
    alignSelf: "flex-end",
    borderRadius: RADIUS.full,
    backgroundColor: PALETTE.orange500,
  },
  scrollView: { flex: 1 },
  scrollContent: { alignItems: "center", paddingBottom: 38 },
  content: { alignSelf: "center" },
  formErrorSummary: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 14,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: COLORS.primarySoft,
  },
  formErrorSummaryTextWrap: {
    flex: 1,
  },
  formErrorSummaryTitle: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.danger,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  formErrorSummaryText: {
    marginTop: 3,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 19,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  reviewCard: {
    width: "100%",
    marginBottom: 22,
    paddingHorizontal: 17,
    paddingVertical: 16,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.dangerSoft,
  },
  reviewHeader: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    gap: 8,
    marginBottom: 7,
  },
  reviewTitle: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  reviewText: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    lineHeight: 22,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  sectionHeader: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 9,
    marginBottom: 18,
  },
  spacedHeader: { marginTop: 25 },
  sectionMarker: {
    width: 4,
    height: 22,
    borderRadius: RADIUS.full,
    backgroundColor: PALETTE.green700,
  },
  sectionTitle: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: PALETTE.green700,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  fieldGroup: { width: "100%", marginBottom: 16, marginTop: 16 },
  inputContainer: {
    width: "100%",
    minHeight: 57,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.iconMuted,
    backgroundColor: PALETTE.neutral25,
  },
  inputContainerError: { borderColor: COLORS.danger },
  pressedField: { opacity: 0.72 },
  input: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 0,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: COLORS.icon,
    writingDirection: "rtl",
  },
  selectText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  selectPlaceholder: { color: PALETTE.neutral600 },
  phoneRow: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 8,
  },
  phoneInputContainer: { flex: 1, width: undefined },
  countryCodeBox: {
    width: 72,
    minHeight: 57,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.placeholder,
    backgroundColor: COLORS.surfaceMuted,
  },
  countryCodeText: { fontFamily: FONTS.medium, fontSize: TYPOGRAPHY.bodyLarge.fontSize, color: COLORS.textMuted },
  textAreaContainer: {
    width: "100%",
    minHeight: 118,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.iconMuted,
    backgroundColor: PALETTE.neutral25,
  },
  textArea: {
    flex: 1,
    minHeight: 92,
    paddingVertical: 0,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    lineHeight: 22,
    color: COLORS.icon,
    writingDirection: "rtl",
  },
  counterText: {
    marginTop: 5,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.iconMuted,
    textAlign: "auto",
  },
  dropdown: {
    width: "100%",
    height: 240,
    overflow: "hidden",
    marginTop: 8,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: PALETTE.neutral0,
  },
  dropdownContent: { flexGrow: 0 },
  dropdownItem: {
    minHeight: 48,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.disabledSurface,
  },
  selectedDropdownItem: { backgroundColor: COLORS.secondarySoft },
  dropdownItemPressed: { opacity: 0.66 },
  dropdownItemText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  mapCard: {
    width: "100%",
    height: 190,
    overflow: "hidden",
    marginTop: 2,
    marginBottom: 10,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.disabledSurface,
  },
  mapCardError: {
    borderColor: COLORS.danger,
  },
  mapPreview: {
    width: "100%",
    height: "100%",
  },
  mapEmptyState: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    backgroundColor: "rgba(233, 238, 232, 0.9)",
  },
  mapEmptyText: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.textMuted,
    textAlign: "center",
    writingDirection: "rtl",
  },
  locationButton: {
    position: "absolute",
    left: 12,
    bottom: 12,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: RADIUS.full,
    backgroundColor: PALETTE.neutral0,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  locationButtonPressed: {
    opacity: 0.72,
    transform: [{ scale: 0.98 }],
  },
  locationButtonText: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.textSecondary,
    writingDirection: "rtl",
  },
  coordinateText: {
    width: "100%",
    marginBottom: 7,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.textMuted,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  helperText: {
    width: "100%",
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    lineHeight: 18,
    color: COLORS.iconMuted,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  subLabel: {
    width: "100%",
    marginBottom: 11,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  subLabelSpacing: { marginTop: 17 },
  choiceWrap: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
  },
  choiceChip: {
    minHeight: 38,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 13,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: COLORS.iconMuted,
    backgroundColor: PALETTE.neutral0,
  },
  selectedChoiceChip: { borderColor: PALETTE.orange500, backgroundColor: PALETTE.orange500 },
  choiceText: { fontFamily: FONTS.regular, fontSize: TYPOGRAPHY.bodySmall.fontSize, color: COLORS.textSecondary },
  selectedChoiceText: { color: PALETTE.neutral0 },
  switchCard: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 18,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.surfaceMuted,
  },
  switchTextWrap: { flex: 1 },
  switchTitle: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  switchSubtitle: {
    marginTop: 4,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    lineHeight: 18,
    color: COLORS.iconMuted,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  logoUploadCard: {
    width: "100%",
    minHeight: 125,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: RADIUS.md,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: COLORS.borderStrong,
    backgroundColor: PALETTE.neutral25,
  },
  logoPreview: { width: 58, height: 58, marginBottom: 8, borderRadius: RADIUS.md },
  logoUploadTitle: {
    marginTop: 5,
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: COLORS.icon,
    textAlign: "center",
    writingDirection: "rtl",
  },
  uploadCard: {
    width: "100%",
    minHeight: 78,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 11,
    marginBottom: 13,
    paddingHorizontal: 13,
    paddingVertical: 12,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: PALETTE.neutral0,
  },
  uploadCardError: { borderColor: COLORS.danger },
  uploadPreview: { width: 44, height: 44, borderRadius: RADIUS.sm },
  uploadTextWrap: { flex: 1 },
  uploadTitle: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  uploadSubtitle: {
    marginTop: 4,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    lineHeight: 16,
    color: COLORS.iconMuted,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  uploadButton: {
    flexShrink: 0,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: PALETTE.orange500,
    backgroundColor: COLORS.dangerSoft,
  },
  uploadButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.primary,
  },
  passwordStrengthHeader: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: -2,
    marginBottom: 7,
  },
  passwordStrengthTitle: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.textMuted,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  passwordStrengthLabel: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.label.fontSize,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  passwordBars: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    gap: 6,
    marginBottom: 15,
  },
  passwordBar: {
    flex: 1,
    height: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.border,
  },
  requirements: {
    width: "100%",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 22,
  },
  requirementRow: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 7,
  },
  requirementText: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  confirmationCard: {
    width: "100%",
    marginTop: 5,
    paddingHorizontal: 14,
    paddingTop: 15,
    paddingBottom: 4,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.surface,
  },
  checkboxRow: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 15,
  },
  checkbox: {
    width: 20,
    height: 20,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
    borderRadius: RADIUS.xs,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: PALETTE.neutral0,
  },
  checkboxSelected: { borderColor: PALETTE.green700, backgroundColor: PALETTE.green700 },
  checkboxText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 20,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  linkText: {
    fontFamily: FONTS.medium,
    color: PALETTE.green700,
    textDecorationLine: "underline",
  },
  errorText: {
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 18,
    color: COLORS.danger,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  submitButton: { width: "100%", height: 58, minHeight: 58, marginTop: 20 },
  submitHelperText: {
    marginTop: 8,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    lineHeight: 18,
    color: COLORS.textMuted,
    textAlign: "center",
    writingDirection: "rtl",
  },
  submitButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.h3.fontSize,
    textAlign: "center",
  },
  loginLink: {
    alignSelf: "center",
    marginTop: 18,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: RADIUS.sm,
  },
  loginLinkPressed: { opacity: 0.55 },
  loginText: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.textMuted,
    textAlign: "center",
    writingDirection: "rtl",
  },
  loginHighlight: { fontFamily: FONTS.medium, color: COLORS.primary },
  mapModalSafeArea: {
    flex: 1,
    backgroundColor: PALETTE.neutral25,
  },
  mapModalHeader: {
    minHeight: 62,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.border,
  },
  mapModalHeaderButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.disabledSurface,
  },
  mapModalHeaderButtonPressed: {
    opacity: 0.65,
    transform: [{ scale: 0.94 }],
  },
  mapModalTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.text,
    textAlign: "center",
    writingDirection: "rtl",
  },
  mapModalHeaderSpacer: {
    width: 46,
    height: 46,
  },
  mapPickerWrap: {
    flex: 1,
  },
  mapPicker: {
    ...StyleSheet.absoluteFillObject,
  },
  mapInstructionCard: {
    position: "absolute",
    top: 14,
    left: 14,
    right: 14,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "flex-start",
    gap: 8,
    paddingHorizontal: 13,
    paddingVertical: 11,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: "rgba(255, 244, 235, 0.96)",
  },
  mapInstructionText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 19,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  currentLocationButton: {
    position: "absolute",
    right: 14,
    bottom: 18,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: PALETTE.neutral0,
  },
  currentLocationButtonPressed: {
    opacity: 0.72,
  },
  currentLocationButtonDisabled: {
    opacity: 0.55,
  },
  currentLocationButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: PALETTE.green700,
    writingDirection: "rtl",
  },
  mapModalFooter: {
    paddingHorizontal: 17,
    paddingTop: 12,
    paddingBottom: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.border,
    backgroundColor: PALETTE.neutral25,
  },
  confirmLocationButton: {
    width: "100%",
    minHeight: 56,
  },
  dateModalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    paddingHorizontal: 16,
    paddingBottom: 24,
    backgroundColor: COLORS.backdrop,
  },
  dateModalCard: {
    overflow: "hidden",
    borderRadius: RADIUS.xl,
    backgroundColor: PALETTE.neutral0,
  },
  dateModalHeader: {
    minHeight: 54,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.border,
  },
  dateModalTitle: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.icon,
    textAlign: "center",
    writingDirection: "rtl",
  },
  dateModalAction: {
    minWidth: 48,
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.sm,
  },
  dateModalCancel: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.textMuted,
  },
  dateModalConfirm: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.primary,
  },
  iosDatePicker: { width: "100%" },
});
