import { StyleSheet } from "react-native";
import { RADIUS, COLORS, FONTS, PALETTE, TYPOGRAPHY } from "@/src/theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  keyboardView: {
    flex: 1,
  },
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  pageHeader: { backgroundColor: COLORS.background },
  topBar: {
    minHeight: 58,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
  },
  topBarTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.text,
    textAlign: "center",
    writingDirection: "rtl",
  },
  topBarSpacer: {
    width: 46,
    height: 46,
  },
  backButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.disabledSurface,
  },
  backButtonPressed: {
    opacity: 0.65,
    transform: [{ scale: 0.94 }],
  },
  progressArea: {
    paddingTop: 4,
    paddingBottom: 18,
  },
  progressLabels: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  progressTitle: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  stepText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.primary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  progressTrack: {
    width: "100%",
    height: 5,
    overflow: "hidden",
    borderRadius: RADIUS.full,
    backgroundColor: PALETTE.neutral250,
  },
  progressFill: {
    width: "66.666%",
    height: "100%",
    alignSelf: "flex-end",
    borderRadius: RADIUS.full,
    backgroundColor: PALETTE.orange500,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignItems: "center",
    paddingBottom: 36,
  },
  content: {
    alignSelf: "center",
  },
  sectionHeader: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 10,
    marginBottom: 18,
  },
  passwordHeader: {
    marginTop: 26,
  },
  sectionMarker: {
    width: 4,
    height: 22,
    borderRadius: RADIUS.full,
    backgroundColor: PALETTE.green700,
  },
  sectionTitle: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: PALETTE.green700,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  fieldGroup: {
    width: "100%",
    marginBottom: 16,
  },
  inputContainer: {
    width: "100%",
    minHeight: 57,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.iconMuted,
    backgroundColor: PALETTE.neutral25,
  },
  inputContainerError: {
    borderColor: COLORS.danger,
  },
  input: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 0,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: COLORS.icon,
    writingDirection: "rtl",
  },
  dateFieldPressed: {
    opacity: 0.72,
  },
  dateValue: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  datePlaceholder: {
    color: PALETTE.neutral600,
  },
  selectText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  selectPlaceholder: {
    color: PALETTE.neutral600,
  },
  phoneRow: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 8,
  },
  phoneInputContainer: {
    flex: 1,
  },
  countryCodeBox: {
    width: 74,
    minHeight: 57,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.iconMuted,
    backgroundColor: PALETTE.neutral25,
  },
  countryCodeText: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: COLORS.textSecondary,
    textAlign: "center",
    writingDirection: "ltr",
  },
  dropdown: {
    width: "100%",
    height: 240,
    overflow: "hidden",
    marginTop: 8,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: PALETTE.neutral0,
  },
  dropdownContent: {
    flexGrow: 0,
  },
  dropdownItem: {
    minHeight: 48,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.disabledSurface,
  },
  selectedDropdownItem: {
    backgroundColor: COLORS.secondarySoft,
  },
  dropdownItemPressed: {
    opacity: 0.65,
  },
  dropdownItemText: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  errorText: {
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 18,
    color: COLORS.danger,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  passwordStrengthHeader: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: -4,
    marginBottom: 8,
  },
  passwordStrengthTitle: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  passwordStrengthLabel: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.label.fontSize,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  passwordBars: {
    width: "100%",
    flexDirection: "row", direction: "rtl",
    gap: 5,
    marginBottom: 18,
  },
  passwordBar: {
    flex: 1,
    height: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.border,
  },
  requirements: {
    width: "100%",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 22,
  },
  requirementRow: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 7,
  },
  requirementText: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  checkboxRow: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "flex-start",
    gap: 12,
    marginTop: 8,
    marginBottom: 16,
  },
  checkbox: {
    width: 21,
    height: 21,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
    borderRadius: RADIUS.xs,
    borderWidth: 1,
    borderColor: COLORS.placeholder,
    backgroundColor: PALETTE.neutral0,
  },
  checkboxSelected: {
    borderColor: PALETTE.green700,
    backgroundColor: PALETTE.green700,
  },
  checkboxText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    lineHeight: 22,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  linkText: {
    fontFamily: FONTS.medium,
    color: COLORS.primary,
  },
  noticeCard: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "flex-start",
    gap: 10,
    marginTop: 6,
    marginBottom: 28,
    paddingHorizontal: 15,
    paddingVertical: 15,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.dangerSoft,
  },
  noticeText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 20,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  dateModalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    paddingHorizontal: 16,
    paddingBottom: 24,
    backgroundColor: COLORS.backdrop,
  },
  dateModalCard: {
    overflow: "hidden",
    borderRadius: RADIUS.xl,
    backgroundColor: PALETTE.neutral0,
  },
  dateModalHeader: {
    minHeight: 54,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.border,
  },
  dateModalTitle: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.icon,
    textAlign: "center",
    writingDirection: "rtl",
  },
  dateModalAction: {
    minWidth: 48,
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.sm,
  },
  dateModalActionPressed: {
    opacity: 0.55,
  },
  dateModalCancel: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.textMuted,
  },
  dateModalConfirm: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.primary,
  },
  iosDatePicker: {
    width: "100%",
  },
  submitButton: {
    width: "100%",
    height: 58,
    minHeight: 58,
  },
  submitButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.h3.fontSize,
    textAlign: "center",
  },
  loginLink: {
    alignSelf: "center",
    marginTop: 18,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: RADIUS.sm,
  },
  loginLinkPressed: {
    opacity: 0.55,
  },
  loginText: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.textMuted,
    textAlign: "center",
    writingDirection: "rtl",
  },
  loginHighlight: {
    fontFamily: FONTS.medium,
    color: COLORS.primary,
  },
});
