import { StyleSheet } from "react-native";

import { TYPOGRAPHY, RADIUS, COLORS, FONTS, PALETTE } from "@/src/theme";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  keyboardView: {
    flex: 1,
  },
  screen: {
    flex: 1,
    width: "100%",
    backgroundColor: COLORS.background,
  },
  scrollView: {
    flex: 1,
    width: "100%",
  },
  pageHeader: { backgroundColor: "transparent" },
  topGlow: {
    position: "absolute",
    backgroundColor: COLORS.divider,
  },
  bottomGlow: {
    position: "absolute",
    backgroundColor: COLORS.divider,
  },
  topBar: {
    width: "100%",
    minHeight: 58,
    flexDirection: "row", direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 4,
  },
  topBarSpacer: {
    width: 46,
    height: 46,
  },
  backButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.disabledSurface,
  },
  backButtonPressed: {
    opacity: 0.65,
    transform: [{ scale: 0.94 }],
  },
  scrollContent: {
    flexGrow: 1,
    width: "100%",
    alignItems: "center",
  },
  content: {
    flexGrow: 1,
    alignSelf: "center",
    justifyContent: "center",
    paddingBottom: 8,
  },
  illustrationContainer: {
    position: "relative",
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
  },
  illustrationHalo: {
    position: "absolute",
    backgroundColor: COLORS.dangerSoft,
  },
  phoneCard: {
    alignItems: "center",
    paddingTop: 7,
    paddingHorizontal: 6,
    paddingBottom: 7,
    backgroundColor: COLORS.border,
    borderWidth: 1.5,
    borderColor: COLORS.textSecondary,
    shadowColor: COLORS.primaryStrong,
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  phoneSpeaker: {
    width: 20,
    height: 3,
    borderRadius: RADIUS.xs,
    backgroundColor: COLORS.primaryStrongFill,
    marginBottom: 6,
  },
  phoneScreen: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.xs,
    backgroundColor: COLORS.dangerSoft,
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  screenKey: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
  },
  phoneHomeIndicator: {
    width: 18,
    height: 3,
    marginTop: 6,
    borderRadius: RADIUS.xs,
    backgroundColor: COLORS.primaryStrongFill,
  },
  codeBubble: {
    position: "absolute",
    right: "15%",
    top: "36%",
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.lg,
    backgroundColor: COLORS.borderStrong,
    borderWidth: 1.5,
    borderColor: COLORS.textSecondary,
  },
  sparkleOne: {
    position: "absolute",
    left: "12%",
    top: "22%",
  },
  header: {
    width: "100%",
    alignItems: "center",
    marginBottom: 24,
  },
  title: {
    fontFamily: FONTS.bold,
    color: COLORS.text,
    textAlign: "center",
  },
  description: {
    maxWidth: 390,
    marginTop: 7,
    fontFamily: FONTS.regular,
    color: COLORS.textMuted,
    textAlign: "center",
  },
  form: {
    width: "100%",
  },
  phoneInfoCard: {
    width: "100%",
    minHeight: 72,
    flexDirection: "row", direction: "rtl",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: RADIUS.lg,
    backgroundColor: PALETTE.neutral0,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
  },
  phoneInfoIcon: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.divider,
  },
  phoneNumber: {
    flex: 1,
    marginHorizontal: 10,
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.icon,
    textAlign: "center",
    writingDirection: "ltr",
  },
  changePhoneButton: {
    minWidth: 48,
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.sm,
  },
  changePhoneText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "center",
  },
  otpSection: {
    width: "100%",
    marginTop: 24,
    marginBottom: 16,
  },
  codeBoxes: {
    position: "relative",
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 30,
    marginBottom: 16,
  },
  codeBox: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PALETTE.neutral0,
    borderWidth: 1.25,
    borderColor: COLORS.borderStrong,
  },
  filledCodeBox: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.surfaceSubtle,
  },
  activeCodeBox: {
    borderWidth: 1.8,
    borderColor: PALETTE.orange500,
  },
  successCodeBox: {
    borderWidth: 2,
    borderColor: COLORS.secondaryStrong,
    backgroundColor: COLORS.secondarySoft,
  },
  errorCodeBox: {
    borderWidth: 2,
    borderColor: COLORS.primaryStrong,
    backgroundColor: COLORS.dangerSoft,
  },
  codeDigit: {
    fontFamily: FONTS.bold,
    color: COLORS.icon,
    textAlign: "center",
  },
  hiddenCodeInput: {
    position: "absolute",
    width: 1,
    height: 1,
    opacity: 0,
  },
  successMessage: {
    width: "100%",
    minHeight: 30,
    flexDirection: "row", direction: "rtl",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    marginBottom: 12,
  },
  successMessageText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    lineHeight: 20,
    color: COLORS.secondaryStrong,
    textAlign: "center",
  },
  codeError: {
    width: "100%",
    flexDirection: "row", direction: "rtl",
    alignItems: "center",
    gap: 7,
    marginBottom: 12,
  },
  codeErrorText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 20,
    color: COLORS.warning,
    textAlign: "auto",
  },
  generalError: {
    width: "100%",
    flexDirection: "row", direction: "rtl",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
    paddingHorizontal: 13,
    paddingVertical: 11,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.primarySoft,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
  },
  generalErrorText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 20,
    color: COLORS.warning,
    textAlign: "auto",
  },
  verifyButton: {
    direction: "ltr",
    width: "100%",
    marginTop: 10,
    paddingVertical: 0,
    shadowColor: COLORS.primaryPressed,
    shadowOffset: {
      width: 0,
      height: 9,
    },
    shadowOpacity: 0.18,
    shadowRadius: 13,
    elevation: 6,
  },
  verifyButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.icon,
    textAlign: "center",
  },
  disabledButtonText: {
    color: PALETTE.neutral0,
  },
  footer: {
    width: "100%",
    alignItems: "center",
    marginTop: 25,
  },
  resendQuestion: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.textSecondary,
    textAlign: "center",
  },
  resendTimer: {
    marginTop: 7,
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "center",
  },
  resendButton: {
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
    paddingHorizontal: 12,
    borderRadius: RADIUS.sm,
  },
  resendButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "center",
  },
  helpMessage: {
    maxWidth: 360,
    flexDirection: "row", direction: "rtl",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 6,
    marginTop: 18,
    paddingHorizontal: 12,
  },
  helpMessageText: {
    flexShrink: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    lineHeight: 18,
    color: COLORS.secondaryStrong,
    textAlign: "center",
  },
  linkPressed: {
    opacity: 0.55,
    transform: [{ scale: 0.96 }],
  },
});

export default styles;
