import type { DailyOpeningHours, ServicePlace } from "@/src/domain/service-places";

const STANDARD_HOURS: DailyOpeningHours[] = [
  { day: 0, open: "09:00", close: "21:00" },
  { day: 1, open: "09:00", close: "21:00" },
  { day: 2, open: "09:00", close: "21:00" },
  { day: 3, open: "09:00", close: "21:00" },
  { day: 4, open: "09:00", close: "21:00" },
  { day: 5, open: "13:00", close: "20:00" },
  { day: 6, open: "09:00", close: "21:00" },
];

const EXTENDED_HOURS: DailyOpeningHours[] = [
  { day: 0, open: "08:00", close: "23:00" },
  { day: 1, open: "08:00", close: "23:00" },
  { day: 2, open: "08:00", close: "23:00" },
  { day: 3, open: "08:00", close: "23:00" },
  { day: 4, open: "08:00", close: "23:00" },
  { day: 5, open: "10:00", close: "22:00" },
  { day: 6, open: "08:00", close: "23:00" },
];

const ALL_DAY_HOURS: DailyOpeningHours[] = [
  { day: 0, open: "00:00", close: "23:59" },
  { day: 1, open: "00:00", close: "23:59" },
  { day: 2, open: "00:00", close: "23:59" },
  { day: 3, open: "00:00", close: "23:59" },
  { day: 4, open: "00:00", close: "23:59" },
  { day: 5, open: "00:00", close: "23:59" },
  { day: 6, open: "00:00", close: "23:59" },
];

/**
 * Development seed only. Replace with backend data without changing the UI.
 */
export const SERVICE_PLACES_SEED: ServicePlace[] = [
  {
    id: "place-clinic-1",
    ownerUserId: "local-user",
    type: "clinic",
    name: "مشفى الشفاء البيطري",
    address: "المزة، دمشق",
    latitude: 33.5036,
    longitude: 36.2525,
    phone: "+963 11 555 0101",
    whatsapp: "+963 944 555 101",
    responsiblePerson: "د. سامر الخطيب",
    emergency24h: true,
    status: "active",
    openingHours: ALL_DAY_HOURS,
    description: "مشفى بيطري يقدم رعاية عامة واستقبال الحالات الطارئة على مدار الساعة.",
    verified: true,
  },
  {
    id: "place-clinic-2",
    type: "clinic",
    name: "عيادة الرحمة البيطرية",
    address: "أبو رمانة، دمشق",
    latitude: 33.5197,
    longitude: 36.2818,
    phone: "+963 11 555 0111",
    whatsapp: "+963 944 555 111",
    responsiblePerson: "د. نادين مراد",
    emergency24h: false,
    status: "active",
    openingHours: STANDARD_HOURS,
    description: "عيادة بيطرية للعناية بالحيوانات الأليفة والاستشارات والحالات العامة.",
    verified: true,
  },
  {
    id: "place-clinic-3",
    type: "clinic",
    name: "عيادة بيت الحيوان",
    address: "المالكي، دمشق",
    latitude: 33.5258,
    longitude: 36.2746,
    phone: "+963 11 555 0122",
    responsiblePerson: "د. يزن محمود",
    emergency24h: false,
    status: "active",
    openingHours: EXTENDED_HOURS,
    description: "رعاية بيطرية يومية مع ساعات عمل ممتدة وخدمة تواصل مباشر.",
    verified: true,
  },
  {
    id: "place-clinic-4",
    type: "clinic",
    name: "مركز الأمل البيطري",
    address: "مشروع دمر، دمشق",
    latitude: 33.5351,
    longitude: 36.2084,
    phone: "+963 11 555 0133",
    responsiblePerson: "د. ريم حمدان",
    emergency24h: false,
    status: "temporarily_closed",
    openingHours: STANDARD_HOURS,
    description: "مركز بيطري محلي لخدمة الحيوانات المنزلية والحالات المحالة.",
    verified: false,
  },
  {
    id: "place-org-1",
    type: "organization",
    name: "جمعية رفق للحيوان",
    address: "أبو رمانة، دمشق",
    latitude: 33.5184,
    longitude: 36.2881,
    phone: "+963 11 555 0102",
    status: "active",
    openingHours: STANDARD_HOURS,
    description: "جمعية إنقاذ ورعاية وتنسيق حالات التبني والحالات الطارئة.",
    verified: true,
  },
  {
    id: "place-shelter-1",
    type: "shelter",
    name: "ملجأ الأمل",
    address: "مشروع دمر، دمشق",
    latitude: 33.5402,
    longitude: 36.2148,
    phone: "+963 11 555 0103",
    status: "active",
    openingHours: STANDARD_HOURS,
    description: "ملجأ مؤقت للحيوانات المنقذة واستقبال الحالات بالتنسيق المسبق.",
  },
  {
    id: "place-store-1",
    type: "pet_store",
    name: "بيت الحيوان للمستلزمات",
    address: "المالكي، دمشق",
    latitude: 33.5293,
    longitude: 36.2711,
    phone: "+963 11 555 0104",
    status: "active",
    openingHours: STANDARD_HOURS,
    description: "طعام، مستلزمات رعاية، وأدوات للحيوانات الأليفة.",
  },
];
