import { StyleSheet } from "react-native";

import { RADIUS, COLORS, FONTS, PALETTE, TYPOGRAPHY } from "@/src/theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: PALETTE.neutral50,
  },
  screen: {
    flex: 1,
    backgroundColor: PALETTE.neutral50,
  },
  topBar: {
    minHeight: 60,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PALETTE.neutral250,
    backgroundColor: PALETTE.neutral50,
  },
  topBarButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.xl,
  },
  topBarTitleWrap: {
    flex: 1,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  topBarTitle: {
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.text,
    textAlign: "center",
    writingDirection: "rtl",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignItems: "center",
    paddingTop: 20,
    paddingBottom: 30,
  },
  content: {
    direction: "rtl",
    alignSelf: "center",
    alignItems: "stretch",
  },
  hero: {
    width: "100%",
    alignItems: "center",
    paddingTop: 4,
    paddingBottom: 8,
  },
  logoBox: {
    width: 82,
    height: 82,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.primary,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  brandRow: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 14,
  },
  brandName: {
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h1.fontSize,
    color: COLORS.icon,
  },
  brandAccent: {
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h1.fontSize,
    color: COLORS.primary,
    marginStart: 1,
    marginEnd: 4,
  },
  tagline: {
    width: "100%",
    marginTop: 5,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.textMuted,
    textAlign: "center",
    writingDirection: "rtl",
  },
  versionPill: {
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.divider,
  },
  versionText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "center",
    writingDirection: "rtl",
  },
  statementCard: {
    width: "100%",
    marginTop: 18,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: PALETTE.neutral0,
  },
  statementHeader: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 8,
  },
  statementTitle: {
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.secondaryStrong,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  visionTitle: {
    color: COLORS.primaryStrong,
  },
  statementText: {
    width: "100%",
    marginTop: 10,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 23,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  featuresCard: {
    width: "100%",
    marginTop: 18,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 20,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: PALETTE.neutral0,
  },
  cardTitle: {
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  featuresGrid: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    flexWrap: "wrap",
    marginTop: 16,
    rowGap: 18,
  },
  featureItem: {
    width: "50%",
    alignItems: "center",
  },
  featureIcon: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.xl,
    backgroundColor: COLORS.infoSoft,
  },
  featureTitle: {
    marginTop: 7,
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.icon,
    textAlign: "center",
    writingDirection: "rtl",
  },
  infoCard: {
    overflow: "hidden",
    width: "100%",
    marginTop: 18,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: PALETTE.neutral250,
    backgroundColor: PALETTE.neutral0,
  },
  infoHeader: {
    flexDirection: "row", direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  infoRow: {
    minHeight: 48,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
  },
  infoLabel: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.textMuted,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  infoValue: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.icon,
  },
  rowBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.border,
  },
  licensesCard: {
    width: "100%",
    marginTop: 18,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: PALETTE.neutral0,
  },
  licensesTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  licensesDescription: {
    width: "100%",
    marginTop: 8,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 21,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  licensesButton: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 15,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: PALETTE.neutral0,
  },
  licensesButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.secondaryStrong,
    textAlign: "center",
    writingDirection: "rtl",
  },
  socialCard: {
    overflow: "hidden",
    width: "100%",
    marginTop: 18,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: PALETTE.neutral250,
    backgroundColor: PALETTE.neutral0,
  },
  socialTitle: {
    paddingHorizontal: 16,
    paddingVertical: 15,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "auto",
    writingDirection: "rtl",
    backgroundColor: COLORS.dangerSoft,
  },
  socialRow: {
    minHeight: 52,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
  },
  socialText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  rowPressed: {
    backgroundColor: COLORS.surface,
  },
  helpCard: {
    direction: "rtl",
    width: "100%",
    alignItems: "stretch",
    marginTop: 18,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: RADIUS.md,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: COLORS.primary,
    backgroundColor: COLORS.dangerSoft,
  },
  helpTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  helpDescription: {
    width: "100%",
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    lineHeight: 18,
    color: COLORS.textMuted,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  helpButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: RADIUS.xs,
  },
  helpButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "auto",
    textDecorationLine: "underline",
    writingDirection: "rtl",
  },
  shareCard: {
    width: "100%",
    alignItems: "stretch",
    marginTop: 18,
    paddingHorizontal: 18,
    paddingVertical: 19,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: COLORS.dangerSoft,
  },
  shareTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  shareDescription: {
    width: "100%",
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    lineHeight: 19,
    color: COLORS.textMuted,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  shareButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 7,
    marginTop: 13,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: RADIUS.xl,
    backgroundColor: PALETTE.neutral0,
  },
  shareButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.primaryStrong,
    writingDirection: "rtl",
  },
  footer: {
    width: "100%",
    alignItems: "center",
    marginTop: 30,
    paddingBottom: 10,
  },
  footerLine: {
    width: 72,
    height: 1,
    backgroundColor: COLORS.border,
  },
  footerCopyright: {
    marginTop: 16,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.iconMuted,
    textAlign: "center",
    writingDirection: "rtl",
  },
  footerLinks: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 14,
    marginTop: 12,
  },
  footerLink: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.secondaryStrong,
    textDecorationLine: "underline",
    writingDirection: "rtl",
  },
  footerDot: {
    width: 3,
    height: 3,
    borderRadius: RADIUS.xs,
    backgroundColor: COLORS.placeholder,
  },
  footerContact: {
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  footerContactText: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.iconMuted,
    textDecorationLine: "underline",
  },
  modalOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    backgroundColor: "rgba(36, 31, 28, 0.42)",
  },
  modalCard: {
    direction: "rtl",
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: RADIUS.lg,
    backgroundColor: PALETTE.neutral0,
  },
  modalHeader: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.lg,
    backgroundColor: COLORS.disabledSurface,
  },
  modalTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  modalText: {
    width: "100%",
    marginTop: 14,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 21,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  licenseList: {
    marginTop: 14,
    gap: 9,
  },
  licenseItem: {
    width: "100%",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: RADIUS.sm,
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    backgroundColor: COLORS.surface,
  },
  modalDoneButton: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 18,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.primaryStrong,
  },
  modalDoneText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: PALETTE.neutral0,
    writingDirection: "rtl",
  },
  pressed: {
    opacity: 0.65,
    transform: [{ scale: 0.98 }],
  },
});
