import { StyleSheet } from "react-native";

import { RADIUS, COLORS, FONTS, PALETTE, TYPOGRAPHY } from "@/src/theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: PALETTE.neutral50,
  },
  screen: {
    flex: 1,
    backgroundColor: PALETTE.neutral50,
  },
  topBar: {
    minHeight: 60,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PALETTE.neutral250,
    backgroundColor: PALETTE.neutral50,
  },
  topBarButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.xl,
  },
  topBarTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.text,
    textAlign: "center",
    writingDirection: "rtl",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignItems: "center",
    paddingTop: 18,
    paddingBottom: 34,
  },
  content: {
    width: "100%",
    direction: "rtl",
    alignSelf: "center",
    alignItems: "stretch",
  },
  heroImage: {
    width: "100%",
    height: 186,
    borderRadius: RADIUS.lg,
    backgroundColor: COLORS.primarySoft,
  },
  heroTextWrap: {
    width: "100%",
    direction: "rtl",
    alignItems: "stretch",
    marginTop: 20,
  },
  heroTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h1.fontSize,
    lineHeight: 33,
    color: COLORS.icon,
    textAlign: "right",
    writingDirection: "rtl",
  },
  heroDescription: {
    width: "100%",
    marginTop: 7,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    lineHeight: 23,
    color: COLORS.textMuted,
    textAlign: "right",
    writingDirection: "rtl",
  },
  formCard: {
    width: "100%",
    direction: "rtl",
    alignItems: "stretch",
    marginTop: 24,
    paddingHorizontal: 18,
    paddingVertical: 20,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: PALETTE.neutral0,
  },
  fieldGroup: {
    width: "100%",
    direction: "rtl",
    alignItems: "stretch",
    marginBottom: 18,
  },
  fieldGroupLast: {
    width: "100%",
    direction: "rtl",
    alignItems: "stretch",
  },
  label: {
    width: "100%",
    marginBottom: 7,
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.textSecondary,
    textAlign: "right",
    writingDirection: "rtl",
  },
  input: {
    width: "100%",
    minHeight: 54,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: PALETTE.neutral0,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "right",
    writingDirection: "rtl",
  },
  ltrInput: {
    textAlign: "left",
    writingDirection: "ltr",
  },
  selectInput: {
    width: "100%",
    minHeight: 54,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: PALETTE.neutral0,
  },
  selectText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "right",
    writingDirection: "rtl",
  },
  selectPlaceholder: {
    color: COLORS.placeholder,
  },
  messageLabelRow: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
  },
  counterText: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.iconMuted,
    textAlign: "left",
    writingDirection: "ltr",
  },
  counterError: {
    color: COLORS.danger,
  },
  messageInput: {
    width: "100%",
    minHeight: 132,
    paddingHorizontal: 15,
    paddingVertical: 14,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: PALETTE.neutral0,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    lineHeight: 22,
    color: COLORS.icon,
    textAlign: "right",
    writingDirection: "rtl",
  },
  inputError: {
    borderColor: COLORS.primaryStrong,
    backgroundColor: COLORS.surfaceSubtle,
  },
  errorText: {
    width: "100%",
    marginTop: 5,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.danger,
    textAlign: "right",
    writingDirection: "rtl",
  },
  uploadBox: {
    width: "100%",
    minHeight: 122,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.md,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: COLORS.borderStrong,
    backgroundColor: COLORS.surfaceSubtle,
  },
  uploadTitle: {
    marginTop: 7,
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.textSecondary,
    textAlign: "center",
    writingDirection: "rtl",
  },
  uploadHint: {
    marginTop: 3,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.iconMuted,
    textAlign: "center",
    writingDirection: "ltr",
  },
  attachmentPreview: {
    width: "100%",
    height: 160,
  },
  removeAttachmentButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
    paddingVertical: 5,
  },
  removeAttachmentText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.danger,
    textAlign: "right",
    writingDirection: "rtl",
  },
  helpCard: {
    width: "100%",
    direction: "rtl",
    alignItems: "stretch",
    marginTop: 20,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: RADIUS.md,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: COLORS.primary,
    backgroundColor: COLORS.dangerSoft,
  },
  helpTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "right",
    writingDirection: "rtl",
  },
  helpDescription: {
    width: "100%",
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    lineHeight: 18,
    color: COLORS.textMuted,
    textAlign: "right",
    writingDirection: "rtl",
  },
  helpButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: RADIUS.xs,
  },
  helpButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "left",
    textDecorationLine: "underline",
    writingDirection: "ltr",
  },
  contactInfoCard: {
    width: "100%",
    direction: "rtl",
    alignItems: "stretch",
    marginTop: 20,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: PALETTE.neutral250,
    backgroundColor: PALETTE.neutral0,
  },
  sectionTitle: {
    width: "100%",
    marginBottom: 12,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.icon,
    textAlign: "right",
    writingDirection: "rtl",
  },
  contactInfoRow: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 12,
    paddingVertical: 10,
  },
  contactTextWrap: {
    flex: 1,
    direction: "rtl",
    alignItems: "stretch",
  },
  contactLabel: {
    width: "100%",
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.iconMuted,
    textAlign: "right",
    writingDirection: "rtl",
  },
  contactValue: {
    width: "100%",
    marginTop: 2,
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "right",
    writingDirection: "rtl",
  },
  contactValueLTR: {
    width: "100%",
    marginTop: 2,
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "left",
    writingDirection: "ltr",
  },
  contactIconOrange: {
    width: 44,
    height: 44,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.xl,
    backgroundColor: COLORS.primarySoft,
  },
  contactIconGreen: {
    width: 44,
    height: 44,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.xl,
    backgroundColor: COLORS.infoSoft,
  },
  contactIconNeutral: {
    width: 44,
    height: 44,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.xl,
    backgroundColor: COLORS.disabledSurface,
  },
  socialCard: {
    width: "100%",
    direction: "rtl",
    alignItems: "stretch",
    marginTop: 20,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: PALETTE.neutral250,
    backgroundColor: PALETTE.neutral0,
  },
  socialGrid: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
  },
  socialItem: {
    width: "24%",
    alignItems: "center",
  },
  socialIcon: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.xl,
    backgroundColor: COLORS.disabledSurface,
  },
  socialLabel: {
    marginTop: 7,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.textSecondary,
    textAlign: "center",
    writingDirection: "rtl",
  },
  submitButton: {
    width: "100%",
    minHeight: 54,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    marginTop: 24,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.primaryStrong,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  submitButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: PALETTE.neutral0,
    textAlign: "center",
    writingDirection: "rtl",
  },
  submitPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  submitDisabled: {
    opacity: 0.55,
  },
  modalOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    backgroundColor: "rgba(36, 31, 28, 0.42)",
  },
  typeModalCard: {
    overflow: "hidden",
    direction: "rtl",
    borderRadius: RADIUS.lg,
    backgroundColor: PALETTE.neutral0,
  },
  modalHeader: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PALETTE.neutral250,
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.lg,
    backgroundColor: COLORS.disabledSurface,
  },
  modalTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.icon,
    textAlign: "right",
    writingDirection: "rtl",
  },
  typeOption: {
    minHeight: 52,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 10,
    paddingHorizontal: 16,
  },
  typeOptionBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.border,
  },
  typeOptionText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "right",
    writingDirection: "rtl",
  },
  rowPressed: {
    backgroundColor: COLORS.surface,
  },
  fieldPressed: {
    opacity: 0.75,
  },
  pressed: {
    opacity: 0.65,
    transform: [{ scale: 0.98 }],
  },
});
