import { StyleSheet } from "react-native";

import { RADIUS, COLORS, FONTS, PALETTE, TYPOGRAPHY } from "@/src/theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: PALETTE.neutral50,
  },
  screen: {
    flex: 1,
    backgroundColor: PALETTE.neutral50,
  },
  topBar: {
    minHeight: 60,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PALETTE.neutral250,
    backgroundColor: PALETTE.neutral50,
  },
  topBarButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.xl,
  },
  topBarTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.text,
    textAlign: "center",
    writingDirection: "rtl",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignItems: "center",
    paddingTop: 18,
  },
  content: {
    alignSelf: "center",
    direction: "rtl",
  },
  heroImage: {
    width: "100%",
    height: 176,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.primarySoft,
  },
  heroTitle: {
    width: "100%",
    marginTop: 15,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: COLORS.icon,
    textAlign: "center",
    writingDirection: "rtl",
  },
  heroDescription: {
    width: "100%",
    marginTop: 5,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.textMuted,
    textAlign: "center",
    writingDirection: "rtl",
  },
  searchContainer: {
    width: "100%",
    minHeight: 52,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 9,
    marginTop: 20,
    paddingHorizontal: 17,
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.divider,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 0,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "right",
    writingDirection: "rtl",
  },
  categoriesGrid: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 12,
    marginTop: 34,
  },
  categoryCard: {
    width: "48.3%",
    minHeight: 98,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: PALETTE.neutral0,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 5,
    elevation: 1,
  },
  categoryIcon: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.xl,
  },
  categoryTitle: {
    marginTop: 8,
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.icon,
    textAlign: "center",
    writingDirection: "rtl",
  },
  section: {
    width: "100%",
    marginTop: 28,
  },
  sectionTitle: {
    width: "100%",
    marginBottom: 12,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h2.fontSize,
    color: COLORS.text,
    textAlign: "right",
    writingDirection: "rtl",
  },
  faqList: {
    gap: 10,
  },
  faqCard: {
    width: "100%",
    paddingHorizontal: 17,
    paddingVertical: 15,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.surfaceMuted,
  },
  faqHeader: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  faqQuestion: {
    flex: 1,
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "right",
    writingDirection: "rtl",
  },
  faqAnswer: {
    width: "100%",
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.border,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 22,
    color: COLORS.textMuted,
    textAlign: "right",
    writingDirection: "rtl",
  },
  articlesCard: {
    overflow: "hidden",
    width: "100%",
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: PALETTE.neutral0,
  },
  articleRow: {
    minHeight: 72,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 11,
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  articleBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.border,
  },
  articlePressed: {
    backgroundColor: COLORS.surface,
  },
  articleIcon: {
    width: 43,
    height: 43,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.disabledSurface,
  },
  articleTextWrap: {
    flex: 1,
  },
  articleTitle: {
    width: "100%",
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "right",
    writingDirection: "rtl",
  },
  articleMeta: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
  },
  articleDuration: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.textMuted,
    writingDirection: "rtl",
  },
  supportCard: {
    width: "100%",
    alignItems: "stretch",
    marginTop: 32,
    paddingHorizontal: 20,
    paddingVertical: 22,
    borderRadius: RADIUS.lg,
    backgroundColor: COLORS.primary,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 4,
  },
  supportTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: PALETTE.neutral0,
    textAlign: "center",
    writingDirection: "rtl",
  },
  supportDescription: {
    width: "100%",
    marginTop: 7,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 20,
    color: COLORS.dangerSoft,
    textAlign: "center",
    writingDirection: "rtl",
  },
  supportPrimaryButton: {
    minHeight: 46,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 18,
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.primaryStrong,
  },
  supportPrimaryText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: PALETTE.neutral0,
    writingDirection: "rtl",
  },
  supportSecondaryButton: {
    minHeight: 46,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 9,
    borderRadius: RADIUS["2xl"],
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.primary,
  },
  supportSecondaryText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: PALETTE.neutral0,
    writingDirection: "rtl",
  },
  linksCard: {
    overflow: "hidden",
    width: "100%",
    marginTop: 28,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.divider,
  },
  linkRow: {
    minHeight: 54,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
  },
  linkText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "right",
    writingDirection: "rtl",
  },
  linkDivider: {
    height: StyleSheet.hairlineWidth,
    marginHorizontal: 16,
    backgroundColor: COLORS.border,
  },
  linkPressed: {
    backgroundColor: COLORS.border,
  },
  footer: {
    width: "100%",
    alignItems: "center",
    marginTop: 40,
    paddingTop: 25,
    paddingBottom: 32,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.border,
  },
  footerLogo: {
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.primaryPressed,
  },
  footerCopyright: {
    marginTop: 13,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.textMuted,
    textAlign: "center",
    writingDirection: "rtl",
  },
  footerLinks: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 20,
    marginTop: 12,
  },
  footerLink: {
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.textMuted,
    textDecorationLine: "underline",
    writingDirection: "rtl",
  },
  emptyCard: {
    width: "100%",
    alignItems: "center",
    marginTop: 28,
    paddingHorizontal: 20,
    paddingVertical: 25,
    borderRadius: RADIUS.lg,
    backgroundColor: PALETTE.neutral0,
  },
  emptyTitle: {
    marginTop: 10,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.icon,
    textAlign: "center",
    writingDirection: "rtl",
  },
  emptyText: {
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 20,
    color: COLORS.textMuted,
    textAlign: "center",
    writingDirection: "rtl",
  },
  emptyButton: {
    marginTop: 15,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: RADIUS.xl,
    backgroundColor: COLORS.primaryStrong,
  },
  emptyButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: PALETTE.neutral0,
    writingDirection: "rtl",
  },
  pressed: {
    opacity: 0.6,
  },
  cardPressed: {
    opacity: 0.75,
    transform: [{ scale: 0.99 }],
  },
  supportPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.99 }],
  },
});
