import { StyleSheet } from "react-native";

import { RADIUS, COLORS, FONTS, PALETTE, TYPOGRAPHY } from "@/src/theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  topBar: {
    minHeight: 60,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.background,
  },
  topBarTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.text,
    textAlign: "center",
    writingDirection: "rtl",
  },
  topBarIconButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.xl,
  },
  iconButtonPressed: {
    opacity: 0.55,
    transform: [{ scale: 0.94 }],
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignItems: "center",
    paddingTop: 15,
    paddingBottom: 28,
  },
  content: {
    alignSelf: "center",
  },
  header: {
    width: "100%",
    alignItems: "center",
    paddingHorizontal: 4,
    marginBottom: 18,
  },
  title: {
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h1.fontSize,
    lineHeight: 32,
    color: COLORS.icon,
    textAlign: "center",
    writingDirection: "rtl",
  },
  updatedText: {
    marginTop: 4,
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.textMuted,
    textAlign: "center",
    writingDirection: "rtl",
  },
  introText: {
    maxWidth: 520,
    marginTop: 12,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    lineHeight: 23,
    color: COLORS.textSecondary,
    textAlign: "center",
    writingDirection: "rtl",
  },
  summaryCard: {
    width: "100%",
    paddingHorizontal: 17,
    paddingVertical: 17,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.infoSoft,
  },
  summaryTitleRow: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 7,
    marginBottom: 13,
  },
  summaryTitle: {
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: COLORS.secondaryStrong,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  summaryList: {
    gap: 9,
  },
  summaryRow: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "flex-start",
    gap: 8,
  },
  summaryText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 19,
    color: COLORS.secondaryStrong,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  contentsCard: {
    width: "100%",
    overflow: "hidden",
    marginTop: 22,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: COLORS.surface,
  },
  contentsTitle: {
    paddingHorizontal: 15,
    paddingVertical: 14,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  contentsRow: {
    minHeight: 46,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    backgroundColor: COLORS.surface,
  },
  contentsRowBorder: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.border,
  },
  contentsRowPressed: {
    backgroundColor: COLORS.disabledSurface,
  },
  contentsItemText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  sectionCard: {
    width: "100%",
    marginTop: 20,
    paddingHorizontal: 17,
    paddingVertical: 18,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: PALETTE.neutral0,
  },
  sectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    lineHeight: 27,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  sectionParagraph: {
    marginTop: 12,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 23,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  informationList: {
    marginTop: 13,
    gap: 15,
  },
  informationItem: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "flex-start",
    gap: 10,
  },
  informationIcon: {
    width: 28,
    alignItems: "center",
    paddingTop: 1,
  },
  informationTextWrap: {
    flex: 1,
  },
  informationTitle: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  informationDescription: {
    marginTop: 3,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    lineHeight: 19,
    color: COLORS.textMuted,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  bulletList: {
    marginTop: 12,
    gap: 10,
  },
  bulletRow: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "flex-start",
    gap: 8,
  },
  bulletDot: {
    width: 5,
    height: 5,
    marginTop: 8,
    borderRadius: RADIUS.xs,
    backgroundColor: COLORS.textMuted,
  },
  bulletText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 21,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  promiseCard: {
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.accent,
    backgroundColor: COLORS.border,
  },
  promiseText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 21,
    color: COLORS.secondaryStrong,
    textAlign: "center",
    writingDirection: "rtl",
  },
  protectionRow: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 14,
    marginTop: 13,
  },
  protectionIcon: {
    width: 58,
    height: 58,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.border,
  },
  protectionText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 22,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  rightsList: {
    marginTop: 14,
    gap: 9,
  },
  rightRow: {
    minHeight: 44,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.surface,
  },
  rightText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 19,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  contactCard: {
    direction: "rtl",
    width: "100%",
    alignItems: "stretch",
    marginTop: 20,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: RADIUS.md,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: COLORS.primary,
    backgroundColor: COLORS.dangerSoft,
  },
  contactTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  contactDescription: {
    width: "100%",
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    lineHeight: 18,
    color: COLORS.textMuted,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  emailButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: RADIUS.xs,
  },
  emailButtonPressed: {
    opacity: 0.55,
  },
  emailText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "left",
    textDecorationLine: "underline",
    writingDirection: "ltr",
  },
  bottomBar: {
    minHeight: 72,
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: PALETTE.neutral250,
    backgroundColor: PALETTE.neutral0,
  },
  bottomBarContent: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 12,
  },
  shareBottomButton: {
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.divider,
  },
  contactButton: {
    flex: 1,
    minHeight: 50,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.primaryStrong,
  },
  contactButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: PALETTE.neutral0,
    textAlign: "center",
  },
  bottomButtonPressed: {
    opacity: 0.75,
    transform: [{ scale: 0.99 }],
  },
});
