import { StyleSheet } from "react-native";

import { RADIUS, COLORS, FONTS, PALETTE, TYPOGRAPHY } from "@/src/theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  topBar: {
    minHeight: 60,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PALETTE.neutral250,
    backgroundColor: COLORS.background,
  },
  topBarButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.xl,
  },
  pressedButton: {
    opacity: 0.55,
    transform: [{ scale: 0.95 }],
  },
  topBarTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.text,
    textAlign: "center",
    writingDirection: "rtl",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignItems: "center",
    paddingTop: 15,
    paddingBottom: 28,
  },
  content: {
    direction: "rtl",
    alignSelf: "center",
    alignItems: "stretch",
  },
  header: {
    direction: "rtl",
    width: "100%",
    alignItems: "stretch",
    marginBottom: 18,
  },
  title: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h1.fontSize,
    lineHeight: 33,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  updatedText: {
    width: "100%",
    marginTop: 4,
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.caption.fontSize,
    color: COLORS.textMuted,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  introText: {
    width: "100%",
    marginTop: 12,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    lineHeight: 23,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  noticeCard: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "flex-start",
    gap: 12,
    paddingHorizontal: 17,
    paddingVertical: 17,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.infoSoft,
  },
  noticeIcon: {
    width: 42,
    height: 42,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.secondaryStrongFill,
  },
  noticeTextWrap: {
    direction: "rtl",
    flex: 1,
    alignItems: "stretch",
  },
  noticeTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: COLORS.secondaryStrong,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  noticeText: {
    width: "100%",
    marginTop: 4,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 20,
    color: COLORS.secondaryStrong,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  contentsCard: {
    direction: "rtl",
    width: "100%",
    overflow: "hidden",
    marginTop: 22,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: COLORS.surface,
  },
  contentsTitle: {
    width: "100%",
    paddingHorizontal: 15,
    paddingVertical: 14,
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.bodySmall.fontSize,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  contentsRow: {
    minHeight: 46,
    alignItems: "stretch",
    justifyContent: "center",
    paddingHorizontal: 15,
    backgroundColor: COLORS.surface,
  },
  contentsRowContent: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  contentsRowBorder: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.border,
  },
  contentsRowPressed: {
    backgroundColor: COLORS.disabledSurface,
  },
  contentsItemText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  sectionCard: {
    direction: "rtl",
    width: "100%",
    alignItems: "stretch",
    marginTop: 20,
    paddingHorizontal: 17,
    paddingVertical: 18,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: PALETTE.neutral0,
  },
  sectionTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    lineHeight: 27,
    color: COLORS.icon,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  sectionParagraph: {
    width: "100%",
    marginTop: 12,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 23,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  warningCard: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "flex-start",
    gap: 8,
    marginTop: 14,
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.primarySoft,
  },
  warningText: {
    flex: 1,
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 21,
    color: COLORS.danger,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  bulletList: {
    width: "100%",
    marginTop: 14,
    gap: 11,
  },
  bulletRow: {
    width: "100%",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "flex-start",
    gap: 9,
  },
  bulletDot: {
    width: 6,
    height: 6,
    marginTop: 8,
    borderRadius: RADIUS.xs,
    backgroundColor: COLORS.textMuted,
  },
  bulletText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.label.fontSize,
    lineHeight: 22,
    color: COLORS.textSecondary,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  inlineContactButton: {
    alignSelf: "flex-end",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 7,
    marginTop: 14,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.dangerSoft,
  },
  inlineContactButtonPressed: {
    opacity: 0.6,
  },
  inlineContactText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.primaryStrong,
    textDecorationLine: "underline",
  },
  helpCard: {
    direction: "rtl",
    width: "100%",
    alignItems: "stretch",
    marginTop: 20,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: RADIUS.md,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: COLORS.primary,
    backgroundColor: COLORS.dangerSoft,
  },
  helpTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: TYPOGRAPHY.h3.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  helpDescription: {
    width: "100%",
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: TYPOGRAPHY.caption.fontSize,
    lineHeight: 18,
    color: COLORS.textMuted,
    textAlign: "auto",
    writingDirection: "rtl",
  },
  helpLink: {
    alignSelf: "flex-start",
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: RADIUS.xs,
  },
  helpLinkPressed: {
    opacity: 0.55,
  },
  helpText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.label.fontSize,
    color: COLORS.primaryStrong,
    textAlign: "left",
    textDecorationLine: "underline",
    writingDirection: "ltr",
  },
  bottomBar: {
    minHeight: 72,
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: PALETTE.neutral250,
    backgroundColor: PALETTE.neutral0,
  },
  bottomContent: {
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    gap: 12,
  },
  shareButton: {
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS["2xl"],
    backgroundColor: COLORS.divider,
  },
  contactButton: {
    flex: 1,
    minHeight: 50,
    flexDirection: "row",
    direction: "rtl",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.primaryStrongFill,
  },
  contactButtonText: {
    fontFamily: FONTS.medium,
    fontSize: TYPOGRAPHY.bodyLarge.fontSize,
    color: PALETTE.neutral0,
    textAlign: "center",
    writingDirection: "rtl",
  },
  bottomPressed: {
    opacity: 0.75,
    transform: [{ scale: 0.99 }],
  },
});
